// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0TP9QgttcirS9YunMDtFq8_G00rhVoHY',
    appId: '1:301006348168:web:b6de0bfa483e8be6ff243d',
    messagingSenderId: '301006348168',
    projectId: 'chemistry-23fcd',
    authDomain: 'chemistry-23fcd.firebaseapp.com',
    storageBucket: 'chemistry-23fcd.firebasestorage.app',
    measurementId: 'G-JXYPC4P6S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvIR6dSjmqIT5EUJgMmaqAKz6CsjGZf4',
    appId: '1:301006348168:android:af5dc682b11aadb1ff243d',
    messagingSenderId: '301006348168',
    projectId: 'chemistry-23fcd',
    storageBucket: 'chemistry-23fcd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfHUQNKA9NS-TQEaAQ_lEnEmi6PuoqpZE',
    appId: '1:301006348168:ios:f572c549b2f4f4c9ff243d',
    messagingSenderId: '301006348168',
    projectId: 'chemistry-23fcd',
    storageBucket: 'chemistry-23fcd.firebasestorage.app',
    iosBundleId: 'com.example.chemistrySimulation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfHUQNKA9NS-TQEaAQ_lEnEmi6PuoqpZE',
    appId: '1:301006348168:ios:f572c549b2f4f4c9ff243d',
    messagingSenderId: '301006348168',
    projectId: 'chemistry-23fcd',
    storageBucket: 'chemistry-23fcd.firebasestorage.app',
    iosBundleId: 'com.example.chemistrySimulation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0TP9QgttcirS9YunMDtFq8_G00rhVoHY',
    appId: '1:301006348168:web:370c8fb8c093e075ff243d',
    messagingSenderId: '301006348168',
    projectId: 'chemistry-23fcd',
    authDomain: 'chemistry-23fcd.firebaseapp.com',
    storageBucket: 'chemistry-23fcd.firebasestorage.app',
    measurementId: 'G-6PEQHEZ7K9',
  );
}
